Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly OfertasLaboralesContext _context;

        public HomeController(ILogger<HomeController> logger ,OfertasLaboralesContext context)
        {
            _context = context;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {

            var ofertasLaborales = await _context.OfertaLaboral.ToListAsync();
            return View(ofertasLaborales);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/OfertasLaboralesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication4.Data;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class OfertasLaboralesController : Controller
    {
        private readonly OfertasLaboralesContext _context;

        public OfertasLaboralesController(OfertasLaboralesContext context)
        {
            _context = context;
        }

        // GET: OfertasLaborales
        public async Task<IActionResult> Index()
        {
            return View(await _context.OfertaLaboral.ToListAsync());
        }

        // GET: OfertasLaborales/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ofertaLaboral = await _context.OfertaLaboral
                .FirstOrDefaultAsync(m => m.idOfertaLaboral == id);
            if (ofertaLaboral == null)
            {
                return NotFound();
            }

            return View(ofertaLaboral);
        }

        // GET: OfertasLaborales/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: OfertasLaborales/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("idOfertaLaboral,Cargo,Vacante,Descripcion,FechaLimite,Salario,Lugar,IdEmpresa")] OfertaLaboral ofertaLaboral)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ofertaLaboral);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(ofertaLaboral);
        }

        // GET: OfertasLaborales/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ofertaLaboral = await _context.OfertaLaboral.FindAsync(id);
            if (ofertaLaboral == null)
            {
                return NotFound();
            }
            return View(ofertaLaboral);
        }

        // POST: OfertasLaborales/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("idOfertaLaboral,Cargo,Vacante,Descripcion,FechaLimite,Salario,Lugar,IdEmpresa")] OfertaLaboral ofertaLaboral)
        {
            if (id != ofertaLaboral.idOfertaLaboral)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ofertaLaboral);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OfertaLaboralExists(ofertaLaboral.idOfertaLaboral))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ofertaLaboral);
        }

        // GET: OfertasLaborales/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ofertaLaboral = await _context.OfertaLaboral
                .FirstOrDefaultAsync(m => m.idOfertaLaboral == id);
            if (ofertaLaboral == null)
            {
                return NotFound();
            }

            return View(ofertaLaboral);
        }

        // POST: OfertasLaborales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ofertaLaboral = await _context.OfertaLaboral.FindAsync(id);
            if (ofertaLaboral != null)
            {
                _context.OfertaLaboral.Remove(ofertaLaboral);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OfertaLaboralExists(int id)
        {
            return _context.OfertaLaboral.Any(e => e.idOfertaLaboral == id);
        }
    }
}

Views/Home/Index.cshtml
@model IEnumerable<WebApplication4.Models.OfertaLaboral>
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class=" display-6">OFERTAS DE EMPLEOS</h1>
    
    <main role="main" class="pb-3">
        <!-- Render  de la ofertas-->
        @Html.Partial("_OfertasParciales", Model)
    </main>

</div>

Views/Home/_OfertasParciales.cshtml
@model IEnumerable<WebApplication4.Models.OfertaLaboral>


<div class="card-group ">

    @foreach (var item in Model)
        {
        <div style="margin: 10px;">
         <div class="card border-info mb-3" style="width: 18rem;">
                <img class="card-img-top" src="/img/img-Trabajo.jpg" alt="Card image cap">
                <div class="card-body" >
                   
                    <h5 class="card-title">@Html.DisplayFor(modelItem => item.Cargo)</h5>
                    <p class="card-text"> <i class="bi bi-geo-alt"> </i> @Html.DisplayFor(modelItem => item.Lugar)</p>
                    
                    <div class="card-title">
                        <h6>@Html.DisplayNameFor(model => model.Salario) $ @Html.DisplayFor(modelItem => item.Salario) </h6>
                    </div>
                    <p class="card-text">
                        <small class="text-muted">
                            Fecha Limite: @item.FechaLimite.ToString("dd/MM/yyyy")
                        </small>
                        
                    </p>
                    <a asp-controller="OfertasLaborales" asp-action="Details" asp-route-id="@item.idOfertaLaboral" class="btn btn-outline-dark">Informacion</a>
                    <a href="#" class="btn btn-outline-dark"><i class="bi bi-box-arrow-in-up-right"></i> Aplicar</a>
                
                </div>
              
         </div>
        </div>                
    }
</div>